title: "Adrián — AI Researcher"
description: "Researcher in Deep Learning, NLP and Biomedical Applications"
theme: jekyll-theme-minimal

logo: /assets/img/profile.jpeg
show_downloads: false

github:
  username: adrian-gude
linkedin: https://linkedin.com/in/adrian
email: adrian@email.com
